language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
services:
  - postgresql
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
